[build]
ignore = "git log -1 --pretty=%B | grep dependabot"
publish = "dist/"
command = "npm start"

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
